// This file is @generated by prost-build.
/// Transport-agnostic node address (iroh NodeAddr equivalent).
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NodeAddress {
    /// REQUIRED. Node ID as hex string (64 characters).
    #[prost(string, tag = "1")]
    pub node_id: ::prost::alloc::string::String,
    /// OPTIONAL. Relay URL the node is reachable through.
    #[prost(string, optional, tag = "2")]
    pub relay_url: ::core::option::Option<::prost::alloc::string::String>,
    /// Direct socket addresses (e.g., "192.168.1.5:12345").
    #[prost(string, repeated, tag = "3")]
    pub direct_addresses: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// Identity information returned by identity RPCs.
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IdentityInfo {
    /// Identity ID (e.g., "obj_2dMiYc8RhnYkorPc5pVh9").
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// Handle (e.g., "@alice").
    #[prost(string, tag = "2")]
    pub handle: ::prost::alloc::string::String,
    /// 8-byte nonce used in ID derivation.
    #[prost(bytes = "vec", tag = "3")]
    pub nonce: ::prost::alloc::vec::Vec<u8>,
}
/// Peer connection information.
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PeerInfo {
    /// Peer's node ID as hex string.
    #[prost(string, tag = "1")]
    pub node_id: ::prost::alloc::string::String,
    /// Peer's relay URL, if known.
    #[prost(string, optional, tag = "2")]
    pub relay_url: ::core::option::Option<::prost::alloc::string::String>,
    /// Human-readable time since last seen (e.g., "2m ago").
    #[prost(string, tag = "3")]
    pub last_seen_ago: ::prost::alloc::string::String,
    /// Connection type: "direct(addr)", "relay(url)", "mixed(addr, url)", or "none".
    #[prost(string, tag = "4")]
    pub connection_type: ::prost::alloc::string::String,
}
/// Project information returned by project RPCs.
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProjectInfo {
    /// Project ID (hex string derived from ReplicaId).
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// Human-readable name.
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// Optional description.
    #[prost(string, optional, tag = "3")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    /// Owner identity ID (e.g., "obj_2dMiYc8RhnYkorPc5pVh9").
    #[prost(string, tag = "4")]
    pub owner_id: ::prost::alloc::string::String,
    /// Unix timestamp (seconds) when project was created.
    #[prost(uint64, tag = "5")]
    pub created_at: u64,
    /// Unix timestamp (seconds) when project was last updated.
    #[prost(uint64, tag = "6")]
    pub updated_at: u64,
}
/// Asset information returned by asset RPCs.
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AssetInfo {
    /// Asset ID (alphanumeric + hyphens, 1-64 characters).
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// Human-readable filename.
    #[prost(string, tag = "2")]
    pub filename: ::prost::alloc::string::String,
    /// MIME type (e.g., "image/png", "model/step").
    #[prost(string, tag = "3")]
    pub content_type: ::prost::alloc::string::String,
    /// Size of the content in bytes.
    #[prost(uint64, tag = "4")]
    pub size: u64,
    /// BLAKE3 hash of the content. Exactly 32 bytes.
    #[prost(bytes = "vec", tag = "5")]
    pub content_hash: ::prost::alloc::vec::Vec<u8>,
    /// Unix timestamp (seconds) when asset was created.
    #[prost(uint64, tag = "6")]
    pub created_at: u64,
}
/// A single entry in the vault catalog.
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VaultEntry {
    /// Project ID (hex string).
    #[prost(string, tag = "1")]
    pub project_id: ::prost::alloc::string::String,
    /// Human-readable project name.
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// Unix timestamp (seconds) when project was created.
    #[prost(uint64, tag = "3")]
    pub created_at: u64,
    /// Whether the project replica exists locally on this device.
    #[prost(bool, tag = "4")]
    pub local: bool,
}
#[derive(
    serde::Serialize, serde::Deserialize, Clone, Copy, PartialEq, Eq, Hash, ::prost::Message,
)]
pub struct HealthRequest {}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HealthResponse {
    /// Status string, "ok" when healthy.
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
}
#[derive(
    serde::Serialize, serde::Deserialize, Clone, Copy, PartialEq, Eq, Hash, ::prost::Message,
)]
pub struct StatusRequest {}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StatusResponse {
    /// Node ID as hex string.
    #[prost(string, tag = "1")]
    pub node_id: ::prost::alloc::string::String,
    /// Full node address with relay and direct addresses.
    #[prost(message, optional, tag = "2")]
    pub node_addr: ::core::option::Option<NodeAddress>,
    /// Number of currently discovered peers.
    #[prost(uint32, tag = "3")]
    pub peer_count: u32,
    /// Identity information, present only if registered.
    #[prost(message, optional, tag = "4")]
    pub identity: ::core::option::Option<IdentityInfo>,
    /// Relay URL the node is connected to.
    #[prost(string, tag = "5")]
    pub relay_url: ::prost::alloc::string::String,
}
#[derive(
    serde::Serialize, serde::Deserialize, Clone, Copy, PartialEq, Eq, Hash, ::prost::Message,
)]
pub struct GetIdentityRequest {}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetIdentityResponse {
    /// The node's current identity.
    #[prost(message, optional, tag = "1")]
    pub identity: ::core::option::Option<IdentityInfo>,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateIdentityRequest {
    /// Handle for the new identity (1-30 chars, lowercase alphanumeric + underscore/period).
    #[prost(string, tag = "1")]
    pub handle: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateIdentityResponse {
    /// The newly created identity.
    #[prost(message, optional, tag = "1")]
    pub identity: ::core::option::Option<IdentityInfo>,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RenameIdentityRequest {
    /// New handle for the identity.
    #[prost(string, tag = "1")]
    pub new_handle: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RenameIdentityResponse {
    /// The identity with updated handle.
    #[prost(message, optional, tag = "1")]
    pub identity: ::core::option::Option<IdentityInfo>,
}
#[derive(
    serde::Serialize, serde::Deserialize, Clone, Copy, PartialEq, Eq, Hash, ::prost::Message,
)]
pub struct ListPeersRequest {}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, ::prost::Message)]
pub struct ListPeersResponse {
    #[prost(message, repeated, tag = "1")]
    pub peers: ::prost::alloc::vec::Vec<PeerInfo>,
}
#[derive(
    serde::Serialize, serde::Deserialize, Clone, Copy, PartialEq, Eq, Hash, ::prost::Message,
)]
pub struct ListProjectsRequest {}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, ::prost::Message)]
pub struct ListProjectsResponse {
    #[prost(message, repeated, tag = "1")]
    pub projects: ::prost::alloc::vec::Vec<ProjectInfo>,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateProjectRequest {
    /// Human-readable project name (1-256 characters).
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// Optional project description (max 4096 characters).
    #[prost(string, optional, tag = "2")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateProjectResponse {
    /// The newly created project.
    #[prost(message, optional, tag = "1")]
    pub project: ::core::option::Option<ProjectInfo>,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetProjectRequest {
    /// Project ID (hex string derived from ReplicaId).
    #[prost(string, tag = "1")]
    pub project_id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetProjectResponse {
    /// The requested project.
    #[prost(message, optional, tag = "1")]
    pub project: ::core::option::Option<ProjectInfo>,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListAssetsRequest {
    /// Project ID to list assets for.
    #[prost(string, tag = "1")]
    pub project_id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, ::prost::Message)]
pub struct ListAssetsResponse {
    #[prost(message, repeated, tag = "1")]
    pub assets: ::prost::alloc::vec::Vec<AssetInfo>,
}
/// Client-streaming upload: first message must be metadata, subsequent messages are chunk_data.
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AddAssetRequest {
    #[prost(oneof = "add_asset_request::Request", tags = "1, 2")]
    pub request: ::core::option::Option<add_asset_request::Request>,
}
/// Nested message and enum types in `AddAssetRequest`.
pub mod add_asset_request {
    #[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Request {
        /// Initial metadata — must be the first message in the stream.
        #[prost(message, tag = "1")]
        Metadata(super::AddAssetMetadata),
        /// File content chunk — sent after metadata.
        #[prost(bytes, tag = "2")]
        ChunkData(::prost::alloc::vec::Vec<u8>),
    }
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AddAssetMetadata {
    /// Project ID to add the asset to.
    #[prost(string, tag = "1")]
    pub project_id: ::prost::alloc::string::String,
    /// Human-readable filename.
    #[prost(string, tag = "2")]
    pub filename: ::prost::alloc::string::String,
    /// MIME type (e.g., "image/png", "model/step").
    #[prost(string, tag = "3")]
    pub content_type: ::prost::alloc::string::String,
    /// Total size of the asset content in bytes.
    #[prost(uint64, tag = "4")]
    pub total_size: u64,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AddAssetResponse {
    /// The newly created asset.
    #[prost(message, optional, tag = "1")]
    pub asset: ::core::option::Option<AssetInfo>,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetAssetContentRequest {
    /// Project ID containing the asset.
    #[prost(string, tag = "1")]
    pub project_id: ::prost::alloc::string::String,
    /// Asset ID to download.
    #[prost(string, tag = "2")]
    pub asset_id: ::prost::alloc::string::String,
}
/// Server-streaming download chunk.
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetAssetContentResponse {
    /// Content bytes.
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    /// MIME type, included in the first chunk only.
    #[prost(string, optional, tag = "2")]
    pub content_type: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateTicketRequest {
    /// Project ID to create a share ticket for.
    #[prost(string, tag = "1")]
    pub project_id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateTicketResponse {
    /// Serialized ticket string for sharing.
    #[prost(string, tag = "1")]
    pub ticket: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RedeemTicketRequest {
    /// Ticket string to redeem.
    #[prost(string, tag = "1")]
    pub ticket: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RedeemTicketResponse {
    /// The project that was joined.
    #[prost(message, optional, tag = "1")]
    pub project: ::core::option::Option<ProjectInfo>,
}
#[derive(
    serde::Serialize, serde::Deserialize, Clone, Copy, PartialEq, Eq, Hash, ::prost::Message,
)]
pub struct ListVaultRequest {}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, ::prost::Message)]
pub struct ListVaultResponse {
    #[prost(message, repeated, tag = "1")]
    pub entries: ::prost::alloc::vec::Vec<VaultEntry>,
}
#[derive(
    serde::Serialize, serde::Deserialize, Clone, Copy, PartialEq, Eq, Hash, ::prost::Message,
)]
pub struct SyncVaultRequest {}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SyncVaultResponse {
    /// Sync status description.
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PullProjectRequest {
    /// Project ID to pull from the vault.
    #[prost(string, tag = "1")]
    pub project_id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PullProjectResponse {
    /// Result status description.
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    /// Project ID that was pulled.
    #[prost(string, tag = "2")]
    pub project_id: ::prost::alloc::string::String,
}
