// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Asset {
    /// REQUIRED. Unique identifier within the project.
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// REQUIRED. Human-readable name.
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// REQUIRED. Identity ID of the asset creator (RFC-001).
    #[prost(string, tag = "3")]
    pub author_id: ::prost::alloc::string::String,
    /// REQUIRED. BLAKE3 hash of the content blob. Exactly 32 bytes.
    #[prost(bytes = "vec", tag = "4")]
    pub content_hash: ::prost::alloc::vec::Vec<u8>,
    /// REQUIRED. Size of the content blob in bytes.
    #[prost(uint64, tag = "5")]
    pub content_size: u64,
    /// OPTIONAL. MIME type or format identifier.
    #[prost(string, tag = "6")]
    pub format: ::prost::alloc::string::String,
    /// REQUIRED. Unix timestamp (seconds) when asset was created.
    #[prost(uint64, tag = "7")]
    pub created_at: u64,
    /// REQUIRED. Unix timestamp (seconds) when asset was last updated.
    #[prost(uint64, tag = "8")]
    pub updated_at: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SignedAsset {
    #[prost(message, optional, tag = "1")]
    pub asset: ::core::option::Option<Asset>,
    #[prost(message, optional, tag = "2")]
    pub signature: ::core::option::Option<::objects_identity::proto::Signature>,
    #[prost(bytes = "vec", tag = "3")]
    pub nonce: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Project {
    /// REQUIRED. Unique identifier (derived from ReplicaId).
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// REQUIRED. Human-readable name.
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// OPTIONAL. Project description.
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    /// REQUIRED. Identity ID of the project owner (RFC-001).
    #[prost(string, tag = "4")]
    pub owner_id: ::prost::alloc::string::String,
    /// REQUIRED. Unix timestamp (seconds) when project was created.
    #[prost(uint64, tag = "5")]
    pub created_at: u64,
    /// REQUIRED. Unix timestamp (seconds) when project was last updated.
    #[prost(uint64, tag = "6")]
    pub updated_at: u64,
}
/// ProjectCatalogEntry represents a project in the user's vault catalog.
/// Stored in user vault replica at key: /catalog/{project_id}
/// STORED ENCRYPTED in vault using XChaCha20-Poly1305
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProjectCatalogEntry {
    /// REQUIRED. Unique project identifier.
    #[prost(string, tag = "1")]
    pub project_id: ::prost::alloc::string::String,
    /// REQUIRED. NamespaceId of the project replica (32 bytes).
    #[prost(bytes = "vec", tag = "2")]
    pub replica_id: ::prost::alloc::vec::Vec<u8>,
    /// REQUIRED. Human-readable project name.
    #[prost(string, tag = "3")]
    pub project_name: ::prost::alloc::string::String,
    /// REQUIRED. Unix timestamp (seconds) when project was created.
    #[prost(uint64, tag = "4")]
    pub created_at: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Reference {
    /// REQUIRED. Unique identifier within the project.
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// REQUIRED. ID of the source asset.
    #[prost(string, tag = "2")]
    pub source_asset_id: ::prost::alloc::string::String,
    /// REQUIRED. ID of the target asset.
    #[prost(string, tag = "3")]
    pub target_asset_id: ::prost::alloc::string::String,
    /// OPTIONAL. BLAKE3 hash of the specific target version.
    #[prost(bytes = "vec", tag = "4")]
    pub target_content_hash: ::prost::alloc::vec::Vec<u8>,
    /// REQUIRED. Type of relationship.
    #[prost(enumeration = "ReferenceType", tag = "5")]
    pub reference_type: i32,
    /// REQUIRED. Unix timestamp (seconds) when reference was created.
    #[prost(uint64, tag = "6")]
    pub created_at: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CrossProjectReference {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub source_asset_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub target_project_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub target_asset_id: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "5")]
    pub target_content_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration = "ReferenceType", tag = "6")]
    pub reference_type: i32,
    #[prost(uint64, tag = "7")]
    pub created_at: u64,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ReferenceType {
    Unspecified = 0,
    Contains = 1,
    DependsOn = 2,
    DerivedFrom = 3,
    References = 4,
}
impl ReferenceType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "REFERENCE_TYPE_UNSPECIFIED",
            Self::Contains => "REFERENCE_TYPE_CONTAINS",
            Self::DependsOn => "REFERENCE_TYPE_DEPENDS_ON",
            Self::DerivedFrom => "REFERENCE_TYPE_DERIVED_FROM",
            Self::References => "REFERENCE_TYPE_REFERENCES",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "REFERENCE_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "REFERENCE_TYPE_CONTAINS" => Some(Self::Contains),
            "REFERENCE_TYPE_DEPENDS_ON" => Some(Self::DependsOn),
            "REFERENCE_TYPE_DERIVED_FROM" => Some(Self::DerivedFrom),
            "REFERENCE_TYPE_REFERENCES" => Some(Self::References),
            _ => None,
        }
    }
}
