//! Protocol Buffer types for OBJECTS Identity Protocol.
//!
//! This file is @generated by prost-build.
//! To regenerate: `cargo build -p objects-identity --features codegen`

#![allow(dead_code)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Identity {
    /// REQUIRED. Identity identifier. Format: "obj_" + 20 base58 characters.
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// REQUIRED. Human-readable handle. 1-30 characters, lowercase alphanumeric,
    /// underscore, and period. Must not start with period or underscore.
    #[prost(string, tag = "2")]
    pub handle: ::prost::alloc::string::String,
    /// REQUIRED. Ed25519 public key. Exactly 32 bytes.
    #[prost(bytes = "vec", tag = "4")]
    pub public_key: ::prost::alloc::vec::Vec<u8>,
    /// REQUIRED. Random nonce used in ID derivation. Exactly 8 bytes.
    #[prost(bytes = "vec", tag = "5")]
    pub nonce: ::prost::alloc::vec::Vec<u8>,
    /// REQUIRED. Unix timestamp (seconds) when identity was created.
    #[prost(uint64, tag = "7")]
    pub created_at: u64,
    /// REQUIRED. Unix timestamp (seconds) when identity was last updated.
    #[prost(uint64, tag = "8")]
    pub updated_at: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Signature {
    /// REQUIRED. Ed25519 signature. Exactly 64 bytes.
    #[prost(bytes = "vec", tag = "1")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    /// REQUIRED. Ed25519 public key. Exactly 32 bytes.
    #[prost(bytes = "vec", tag = "2")]
    pub public_key: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateIdentityRequest {
    #[prost(string, tag = "1")]
    pub handle: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub public_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "4")]
    pub nonce: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "5")]
    pub signature: ::core::option::Option<Signature>,
    #[prost(uint64, tag = "6")]
    pub timestamp: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ChangeHandleRequest {
    #[prost(string, tag = "1")]
    pub identity_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub new_handle: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub signature: ::core::option::Option<Signature>,
    #[prost(uint64, tag = "4")]
    pub timestamp: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetIdentityRequest {
    #[prost(string, tag = "1")]
    pub identity_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResolveIdentityRequest {
    #[prost(oneof = "resolve_identity_request::Query", tags = "1, 2")]
    pub query: ::core::option::Option<resolve_identity_request::Query>,
}
/// Nested message and enum types in `ResolveIdentityRequest`.
pub mod resolve_identity_request {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Query {
        #[prost(string, tag = "1")]
        Handle(::prost::alloc::string::String),
        #[prost(bytes, tag = "2")]
        PublicKey(::prost::alloc::vec::Vec<u8>),
    }
}
